version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: user_mysqlDB
    environment:
      MYSQL_ROOT_PASSWORD: VERY_SECURE_PASSWORD
      MYSQL_DATABASE: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: VERY_SECURE_PASSWORD
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "user", "--password=VERY_SECURE_PASSWORD"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  user_microservice:
    build:
      context: ./User_Microservice
      dockerfile: Dockerfile
    container_name: user_microservice
    environment:
      DB_USER: user
      DB_PASSWORD: VERY_SECURE_PASSWORD
      DB_HOST: mysql
      DB_NAME: user_db
      DB_PORT: 3306
      AWS_REGION: eu-north-1
      COGNITO_USERPOOL_ID: eu-north-1_BZVwENxbX
      COGNITO_APP_CLIENT_ID: 1ks0163ckccdfje0a1h7h78ffl
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge