version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: user_mysqlDB
    environment:
      MYSQL_ROOT_PASSWORD: VERY_SECURE_PASSWORD
      MYSQL_DATABASE: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: VERY_SECURE_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge