/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_cognito_identity_pool_id": "eu-north-1:e475481d-3b97-4317-8635-34a70af1fc92",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_BZVwENxbX",
    "aws_user_pools_web_client_id": "6ffdahqhmbv87o1suueqpqhkkp",
    oauth: {
        domain: 'https://homeharmony.auth.eu-north-1.amazoncognito.com',
        scope: ['email', 'openid', 'profile'],
        redirectSignIn: 'https://13.51.235.59', 
        redirectSignOut: 'https://13.51.235.59', 
        responseType: 'code'
    },
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
