name: Build
on:
  push:
    branches:
      - main
      - SCRUM-13-Save-users-to-DB
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: Test and SonarCloud Scan
    runs-on: ubuntu-latest
    services:
      mysql_test:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: test_password
          MYSQL_DATABASE: test_user_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3307:3306  # Expose different port for testing DB

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures complete history for better analysis

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use your project's Python version

      - name: Wait for MySQL to be Ready
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..30}; do
            mysqladmin ping -h 127.0.0.1 -P 3307 -u test_user --password=test_password && break
            echo "MySQL not ready yet..."
            sleep 5
          done

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./User_MicroService/requirements.txt

      - name: Move to the correct directory
        run: cd ./User_MicroService/app

      - name: Run Tests
        env:
          DATABASE_URL: mysql://test_user:test_password@127.0.0.1:3307/test_user_db  # Update this based on how your code configures DB connections
        run: |
          pytest -cov-report=xml  # Runs tests and generates coverage report in XML

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}